package:
  name: robotraconteur_training_sim
  version: 0.1.0

source:
  git_url: https://github.com/robotraconteur-contrib/robotraconteur_training_sim.git
  git_depth: 1

requirements:
  host:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo_model_robotraconteur_driver
    - pyyaml
  run:
    - robotraconteur
    - robotraconteur_companion
    - gazebo
    - gazebo_robotraconteur_server_plugin
    - gazebo_model_robotraconteur_driver
    - pyyaml

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: "Gazebo based training simulator for Robot Raconteur"