package:
  name: robotraconteur_companion
  version: 0.1.0

source:
  git_url: https://github.com/robotraconteur/robotraconteur_companion.git
  git_depth: 1

requirements:
  host:
    - robotraconteur
    - git
    - cmake
    - boost-cpp==1.74.0
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - yaml-cpp
    - eigen
  run:
    - boost-cpp
    - robotraconteur

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: 'Companion library for the Robot Raconteur core library'

