package:
  name: robotraconteur
  version: 0.15.1

source:
  url: https://github.com/robotraconteur/robotraconteur/archive/v0.15.1.tar.gz
  sha256: 2fd45f319e33162f04cbc946edf96aea3eff736744b66c8c9f17817c7667348e

requirements:
  host:
    - git
    - cmake
    - boost-cpp==1.74.0
    - python==3.8
    - swig
    - numpy
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pip
  run:
    - boost-cpp==1.74.0
    - python==3.8
    - numpy

about:
  home: http://robotraconteur.com
  license: Apache 2.0
  summary: 'Communication framework for robotics and automation'

